from __future__ import annotations
import argparse
from pathlib import Path

def build_base_qlearning_parser(description: str) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("--config", type=Path, default=None)
    parser.add_argument("--output-root", type=Path, default=Path("outputs"))
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--n-agents", type=int, default=3)
    parser.add_argument("--episode-length", type=int, default=500)
    parser.add_argument("--total-timesteps", type=int, default=200_000)
    parser.add_argument("--buffer-size", type=int, default=200_000)
    parser.add_argument("--batch-size", type=int, default=2048)
    parser.add_argument("--start-learning", type=int, default=1_000)
    parser.add_argument("--train-interval", type=int, default=1)
    parser.add_argument("--learning-rate", type=float, default=5e-4)
    parser.add_argument("--gamma", type=float, default=0.99)
    parser.add_argument("--target-update-interval", type=int, default=500)
    parser.add_argument("--grad-clip-norm", type=float, default=1.0)
    parser.add_argument("--double-q", action="store_true")
    parser.add_argument("--optimizer", type=str, default="rmsprop", choices=["adam", "rmsprop"])
    parser.add_argument("--epsilon-start", type=float, default=1.0)
    parser.add_argument("--epsilon-end", type=float, default=0.05)
    parser.add_argument("--epsilon-decay-steps", type=int, default=100_000)
    parser.add_argument("--hidden-dims", type=int, nargs="+", default=[128, 128])
    parser.add_argument("--activation", type=str, default="tanh", choices=["relu", "tanh", "elu"])
    parser.add_argument("--layer-norm", action="store_true")
    parser.add_argument("--dueling", action="store_true")
    parser.add_argument("--stream-hidden-dim", type=int, default=64)
    parser.add_argument("--no-agent-id", action="store_true")
    parser.add_argument("--independent-agents", action="store_true")
    obs_norm_group = parser.add_mutually_exclusive_group()
    obs_norm_group.add_argument("--normalize-obs", action="store_true")
    obs_norm_group.add_argument("--no-normalize-obs", action="store_false", dest="normalize_obs")
    parser.add_argument("--obs-norm-clip", type=float, default=5.0)
    parser.add_argument("--obs-norm-eps", type=float, default=1e-8)
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--log-interval", type=int, default=10)
    parser.add_argument("--eval-freq", type=int, default=5000)
    parser.add_argument("--n-eval-episodes", type=int, default=30)
    parser.set_defaults(normalize_obs=True)
    return parser

def add_team_reward_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--team-reward", action="store_true")

def add_qmix_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--mixer-hidden-dim", type=int, default=32)
    parser.add_argument("--hypernet-hidden-dim", type=int, default=64)

def add_qplex_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--mixing-embed-dim", type=int, default=32)
    parser.add_argument("--hypernet-embed", type=int, default=64)
    parser.add_argument("--adv-hypernet-layers", type=int, default=3)
    parser.add_argument("--adv-hypernet-embed", type=int, default=64)
    parser.add_argument("--num-kernel", type=int, default=10)
    parser.add_argument("--n-head", type=int, default=4)
    parser.add_argument("--attend-reg-coef", type=float, default=0.001)
    parser.add_argument("--nonlinear", action="store_true")
    parser.add_argument("--mask-dead", action="store_true")
    parser.add_argument("--no-weighted-head", action="store_false", dest="weighted_head")
    parser.add_argument("--no-state-bias", action="store_false", dest="state_bias")
    parser.add_argument("--no-is-minus-one", action="store_false", dest="is_minus_one")
    parser.set_defaults(weighted_head=True, state_bias=True, is_minus_one=True)

def build_mappo_parser(description: str) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("--config", type=Path, default=None)
    parser.add_argument("--output-root", type=Path, default=Path("outputs"))
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--n-agents", type=int, default=3)
    parser.add_argument("--episode-length", type=int, default=500)
    parser.add_argument("--total-timesteps", type=int, default=200_000)
    parser.add_argument("--n-envs", type=int, default=8)
    parser.add_argument("--n-steps", type=int, default=500)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--n-epochs", type=int, default=4)
    parser.add_argument("--learning-rate", type=float, default=3e-4)
    parser.add_argument("--gamma", type=float, default=0.99)
    parser.add_argument("--gae-lambda", type=float, default=0.95)
    parser.add_argument("--clip-range", type=float, default=0.2)
    parser.add_argument("--ent-coef", type=float, default=0.01)
    parser.add_argument("--vf-coef", type=float, default=0.5)
    parser.add_argument("--huber-delta", type=float, default=10.0)
    parser.add_argument("--value-norm-beta", type=float, default=0.999)
    parser.add_argument("--max-grad-norm", type=float, default=1.0)
    parser.add_argument("--hidden-dims", type=int, nargs="+", default=[128, 128])
    parser.add_argument("--activation", type=str, default="tanh", choices=["relu", "tanh", "elu"])
    parser.add_argument("--layer-norm", action="store_true")
    parser.add_argument("--no-agent-id", action="store_true")
    parser.add_argument("--team-reward", action="store_true")
    obs_norm_group = parser.add_mutually_exclusive_group()
    obs_norm_group.add_argument("--normalize-obs", action="store_true")
    obs_norm_group.add_argument("--no-normalize-obs", action="store_false", dest="normalize_obs")
    parser.add_argument("--obs-norm-clip", type=float, default=5.0)
    parser.add_argument("--obs-norm-eps", type=float, default=1e-8)
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--log-interval", type=int, default=10)
    parser.add_argument("--eval-freq", type=int, default=5000)
    parser.add_argument("--n-eval-episodes", type=int, default=30)
    parser.set_defaults(normalize_obs=True)
    return parser
